name: Test
on:
  push:
    branches: [main]
  pull_request:
jobs:
  test:
    name: Test
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        runs-on: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: ./
      - run: cloudflared --help
      - run: tmux -V
